-- =====================================================================
-- V6: histórico de alterações (spec 003, R1; docs/adr/0021)
--
-- O Hibernate Envers grava, a cada transação que muda um dado auditado,
-- uma revisão (quem, de qual organização, quando, com qual rastreio) e
-- uma cópia do registro como ficou, nas tabelas com o sufixo _aud.
--
-- As colunas das tabelas _aud são as mesmas das tabelas de origem, todas
-- opcionais, menos as de credencial (senha_hash, token_hash), que nunca
-- entram no histórico. Também ficam de fora as marcas de leitura da
-- negociação, que mudam a cada visita e não são uma decisão de ninguém.
--
-- Sem chave estrangeira para as tabelas de negócio: o histórico continua
-- válido mesmo depois de o registro original ser apagado.
-- =====================================================================

CREATE TABLE tb_revisao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    momento         BIGINT      NOT NULL,
    usuario_id      UUID,
    organizacao_id  UUID,
    trace_id        VARCHAR(32),
    origem          VARCHAR(10) NOT NULL,
    CONSTRAINT pk_revisao PRIMARY KEY (id),
    CONSTRAINT ck_revisao_origem CHECK (origem IN ('PESSOA', 'PUBLICO', 'SISTEMA'))
);

CREATE INDEX idx_revisao_organizacao ON tb_revisao (organizacao_id, momento);
CREATE INDEX idx_revisao_usuario ON tb_revisao (usuario_id);

-- Quais entidades mudaram em cada revisão (a atividade lê por aqui)
CREATE TABLE tb_revisao_entidade (
    revisao_id BIGINT       NOT NULL,
    entidade   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_revisao_entidade PRIMARY KEY (revisao_id, entidade),
    CONSTRAINT fk_revisao_entidade_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_organizacao_aud (
    id           UUID         NOT NULL,
    revisao_id   BIGINT       NOT NULL,
    tipo_revisao SMALLINT,
    tipo         VARCHAR(20),
    razao_social VARCHAR(200),
    cnpj         VARCHAR(14),
    criada_em    TIMESTAMP(6),
    CONSTRAINT pk_organizacao_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_organizacao_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_usuario_aud (
    id            UUID         NOT NULL,
    revisao_id    BIGINT       NOT NULL,
    tipo_revisao  SMALLINT,
    nome          VARCHAR(150),
    email         VARCHAR(100),
    superadmin    BOOLEAN,
    criado_em     TIMESTAMP(6),
    desativado_em TIMESTAMP(6),
    CONSTRAINT pk_usuario_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_usuario_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_membro_aud (
    id             UUID         NOT NULL,
    revisao_id     BIGINT       NOT NULL,
    tipo_revisao   SMALLINT,
    usuario_id     UUID,
    organizacao_id UUID,
    papel          VARCHAR(20),
    criado_em      TIMESTAMP(6),
    removido_em    TIMESTAMP(6),
    CONSTRAINT pk_membro_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_membro_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_convite_aud (
    id             UUID                        NOT NULL,
    revisao_id     BIGINT                      NOT NULL,
    tipo_revisao   SMALLINT,
    organizacao_id UUID,
    nome           VARCHAR(150),
    email          VARCHAR(100),
    convidado_por  UUID,
    criado_em      TIMESTAMP(6) WITH TIME ZONE,
    expira_em      TIMESTAMP(6) WITH TIME ZONE,
    aceito_em      TIMESTAMP(6) WITH TIME ZONE,
    cancelado_em   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_convite_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_convite_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_cotacao_aud (
    id                 UUID           NOT NULL,
    revisao_id         BIGINT         NOT NULL,
    tipo_revisao       SMALLINT,
    nome_servico       VARCHAR(200),
    requisitos         VARCHAR(1000),
    categoria          VARCHAR(30),
    orcamento_estimado NUMERIC(15, 2),
    data_criacao       TIMESTAMP(6),
    data_limite        TIMESTAMP(6),
    status             VARCHAR(255),
    empresa_id         UUID,
    criada_por         UUID,
    CONSTRAINT pk_cotacao_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_cotacao_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_proposta_aud (
    id             UUID           NOT NULL,
    revisao_id     BIGINT         NOT NULL,
    tipo_revisao   SMALLINT,
    valor_proposto NUMERIC(15, 2),
    descricao      VARCHAR(1000),
    status         VARCHAR(255),
    data_envio     TIMESTAMP(6),
    fornecedor_id  UUID,
    enviada_por    UUID,
    cotacao_id     UUID,
    CONSTRAINT pk_proposta_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_proposta_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

CREATE TABLE tb_negociacao_aud (
    id               UUID           NOT NULL,
    revisao_id       BIGINT         NOT NULL,
    tipo_revisao     SMALLINT,
    valor_final      NUMERIC(15, 2),
    status           VARCHAR(255),
    data_hora_inicio TIMESTAMP(6),
    datafinalizacao  DATE,
    proposta_id      UUID,
    empresa_id       UUID,
    fornecedor_id    UUID,
    CONSTRAINT pk_negociacao_aud PRIMARY KEY (id, revisao_id),
    CONSTRAINT fk_negociacao_aud_revisao FOREIGN KEY (revisao_id) REFERENCES tb_revisao (id)
);

-- O histórico de um registro é sempre lido pelo id dele
CREATE INDEX idx_cotacao_aud_revisao ON tb_cotacao_aud (revisao_id);
CREATE INDEX idx_proposta_aud_revisao ON tb_proposta_aud (revisao_id);
CREATE INDEX idx_negociacao_aud_revisao ON tb_negociacao_aud (revisao_id);
CREATE INDEX idx_membro_aud_revisao ON tb_membro_aud (revisao_id);
CREATE INDEX idx_convite_aud_revisao ON tb_convite_aud (revisao_id);
